# HTTP Server
quarkus.http.port=8083
quarkus.http.host=0.0.0.0

#FOR DEV (webapp)
#quarkus.http.cors=true
#quarkus.http.cors.origins=*
#quarkus.http.cors.methods=*
#quarkus.http.cors.headers=*

# Flyway Configuration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

# Datasource Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/shoppinglist
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# RabbitMQ
rabbitmq.host=rabbitmq
rabbitmq.port=5672
rabbitmq.username=${RABBITMQ_USER}
rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.queue=recipe-info-queue

mp.messaging.connector.smallrye-rabbitmq.host=${rabbitmq.host}
mp.messaging.connector.smallrye-rabbitmq.port=${rabbitmq.port}
mp.messaging.connector.smallrye-rabbitmq.username=${rabbitmq.username}
mp.messaging.connector.smallrye-rabbitmq.password=${rabbitmq.password}

# OIDC Configuration
quarkus.oidc.auth-server-url=https://admin.loveyourmeal.cloud/realms/recipeapp
quarkus.oidc.client-id=recipeapp
quarkus.oidc.credentials.secret=${OIDC_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=https://admin.loveyourmeal.cloud/realms/recipeapp
quarkus.oidc.roles.source=accesstoken

# Security
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Docker Container Image
quarkus.container-image.build=true
quarkus.container-image.push=false
quarkus.container-image.registry=docker.io
quarkus.container-image.group=myapp
quarkus.container-image.name=shopping-list
quarkus.container-image.tag=1.0.0-SNAPSHOT

# Console
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n

quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=logstash
quarkus.log.handler.gelf.port=5000
quarkus.log.handler.gelf.include-full-mdc=true
quarkus.log.handler.gelf.include-location=true

# Optional: Console Logging
quarkus.log.console.json=false
quarkus.log.level=INFO